apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: outside-whale-python 
  janus-idp.io/tekton: outside-whale-python
  backstage.io/kubernetes-id: outside-whale-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: outside-whale-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  